### PR TITLE
Exit publishing early if only invalid change files are present

### LINKED ISSUE #597: Publishing should exit early if only invalid change files are present
In Fluent UI we've had a few instances when our release build failed because change files existed but were all invalid, which results in no actual changes to publish. The logs for this case are extremely uninformative.

Fix is to update whichever part of the code checks whether to enter the publish step to also verify that at least one valid change file exists.

Additionally/alternatively, it might be good to add an option like `failOnInvalidChangeFiles` to (mostly) prevent such files from being checked in--right now it's just treated as a warning by `beachball check`.

<details>
<summary>expand for full log</summary>
```
> fluent-ui-react-repo@1.0.0 publish:beachball /mnt/work/5/s
> beachball publish --scope "!packages/fluentui/*" "-b" "origin/master" "-n" "***" "--access" "public" "-y"

Invalid change file detected (non-existent package or private package); delete this file "/mnt/work/5/s/change/@fluentui-react-examples-292153ef-66f4-43d3-b6e7-8817fdcf814c.json"
Invalid change file detected (non-existent package or private package); delete this file "/mnt/work/5/s/change/@fluentui-react-examples-407aa3fb-fb16-444c-b15f-3e491cd2d8ba.json"
Invalid change file detected (non-existent package or private package); delete this file "/mnt/work/5/s/change/@fluentui-react-examples-5f8fef9b-5486-4d10-8ed5-527cbd34ff54.json"
Validating no private package among package dependencies OK!
Publishing with the following configuration:

  registry: https://registry.npmjs.org/

  current branch: HEAD
  current hash: 1e5b888607626cae4ff69b5b9055bf8b9537c45b
  target branch: origin/master
  tag: latest

  bumps versions: yes
  publishes to npm registry: yes
  pushes to remote git repo: yes


creating temporary publish branch publish_1631720628491
Bumping version for npm publish
Invalid change file detected (non-existent package or private package); delete this file "/mnt/work/5/s/change/@fluentui-react-examples-292153ef-66f4-43d3-b6e7-8817fdcf814c.json"
Invalid change file detected (non-existent package or private package); delete this file "/mnt/work/5/s/change/@fluentui-react-examples-407aa3fb-fb16-444c-b15f-3e491cd2d8ba.json"
Invalid change file detected (non-existent package or private package); delete this file "/mnt/work/5/s/change/@fluentui-react-examples-5f8fef9b-5486-4d10-8ed5-527cbd34ff54.json"
Validating no private package among package dependencies OK!
Trying to push to git. Attempt 1/5
Reverting
Fetching from remote
Bumping the versions for git push
mergePublishBranch (2 / 4) - trying to run "git commit -m applying package updates"
On branch publish_1631720628491
nothing to commit, working tree clean
ℹ No staged files found.
[WARN 1/5]: merging to target has failed!
Trying to push to git. Attempt 2/5
Reverting
Fetching from remote
Bumping the versions for git push
mergePublishBranch (2 / 4) - trying to run "git commit -m applying package updates"
On branch publish_1631720628491
nothing to commit, working tree clean
ℹ No staged files found.
[WARN 2/5]: merging to target has failed!
Trying to push to git. Attempt 3/5
Reverting
Fetching from remote
Bumping the versions for git push
mergePublishBranch (2 / 4) - trying to run "git commit -m applying package updates"
On branch publish_1631720628491
nothing to commit, working tree clean
ℹ No staged files found.
[WARN 3/5]: merging to target has failed!
Trying to push to git. Attempt 4/5
Reverting
Fetching from remote
Bumping the versions for git push
mergePublishBranch (2 / 4) - trying to run "git commit -m applying package updates"
On branch publish_1631720628491
nothing to commit, working tree clean
ℹ No staged files found.
[WARN 4/5]: merging to target has failed!
Trying to push to git. Attempt 5/5
Reverting
Fetching from remote
Bumping the versions for git push
mergePublishBranch (2 / 4) - trying to run "git commit -m applying package updates"
On branch publish_1631720628491
nothing to commit, working tree clean
ℹ No staged files found.
[WARN 5/5]: merging to target has failed!
Something went wrong with the publish! Manually update these package and versions:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fluent-ui-react-repo@1.0.0 publish:beachball: `beachball publish --scope "!packages/fluentui/*" "-b" "origin/master" "-n" "***" "--access" "public" "-y"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fluent-ui-react-repo@1.0.0 publish:beachball script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/devops/.npm/_logs/##[error]Bash exited with code '1'.
##[section]Finishing: Publish changes and bump versions
```
</details>

### PR DESCRIPTION
**Pull request by ecraig12345**
If a package had only invalid change files (packages that were private or didn't exist), beachball would start the publish process but then fail partway through because there was nothing to commit. `getBumpInfo` had attempted to filter out those files, but by that point it was too late because the publish process had already started.

This PR fixes the issue at the root by modifying `readChangeFiles` to exclude (and warn about) any change files from private or nonexistent packages. 

Fixes #597

### CODE REVIEW

File: src/bump/gatherBumpInfo.ts [hunk 1]
```diff
@@ -4,53 +4,20 @@ import { BumpInfo } from '../types/BumpInfo';
...
 function gatherPreBumpInfo(options: BeachballOptions, packageInfos: PackageInfos): BumpInfo {
-  const { path: cwd } = options;
   // Collate the changes per package
   const changes = readChangeFiles(options, packageInfos);
-  const changePath = getChangePath(cwd);
 
   // const dependentChangeTypes: BumpInfo['dependentChangeTypes'] = {};
   const groupOptions = {};
 
-  // Clear changes for non-existent and accidental private packages
```
Comment (ecraig12345) [inline src/bump/gatherBumpInfo.ts:20]: Removed this filtering because it's now handled earlier, in `readChangeFiles`

**Review by kenotron — APPROVED** [review]
